feat: add ts types
multiformats/js-multibase pull request #72
Opened 2020-11-18 15:41 UTC by hugomrdias

2020-11-19 07:06 UTC, Gozala requested changes
Mostly nits & suggestions. Only thing I do feel strongly about is type names that I think should be singular instead of plural.

I also flagged out few things with ⚠️ which appear to be breaking changes and might be worth reconsideration.

With type names changed 👍from me and no need for another review cycle.

2020-11-19 07:06 UTC, Gozala commented on src/index.js
> +/** @typedef {import("./types").BaseNamesCodes} BaseNamesCodes */
```suggestion
/** @typedef {import("./types").BaseNameOrCode} BaseNameOrCode */
```

2020-11-19 07:06 UTC, Gozala commented on src/index.js
> +/** @typedef {import("./types").BaseCodes} BaseCodes */
```suggestion
/** @typedef {import("./types").BaseCode} BaseCode */
```

2020-11-19 07:06 UTC, Gozala commented on src/constants.js
> +}, /** @type {Record<BaseCodes,Base>} */({}))
```suggestion
}, /** @type {Record<BaseCode, Base>} */({}))
```

2020-11-19 07:06 UTC, Gozala commented on src/constants.js
> +}, /** @type {Record<BaseNames,Base>} */({}))
```suggestion
}, /** @type {Record<BaseName, Base>} */({}))
```

2020-11-19 07:06 UTC, Gozala commented on src/constants.js
> + * @type {Array<[BaseNames, BaseCodes, CodecFactory, string]>}
```suggestion
 * @type {Array<[BaseName, BaseCode, CodecFactory, string]>}
```

2020-11-19 07:06 UTC, Gozala commented on src/constants.js
> +/** @typedef {import('./types').BaseNames} BaseNames */
```suggestion
/** @typedef {import('./types').BaseName} BaseName */
```

2020-11-19 07:06 UTC, Gozala commented on src/constants.js
> +/** @typedef {import('./types').BaseCodes} BaseCodes */
```suggestion
/** @typedef {import('./types').BaseCode} BaseCode */
```

2020-11-19 10:51 UTC, hugomrdias commented on README.md
>  https://multiformats.github.io/js-multibase/
Suggestions ?

2020-11-19 10:57 UTC, hugomrdias commented on src/util.js
> +// @ts-ignore
well

error TS2339: Property 'TextDecoder' does not exist on type 'typeof import("/Users/hd/code/pl/js-multibase/node_modules/web-encoding/src/lib")'.

2020-11-19 16:40 UTC, Gozala commented on README.md
>  https://multiformats.github.io/js-multibase/
I don’t know maybe API Docs badge at the top ?

2020-11-19 16:44 UTC, Gozala approved these changes

2020-11-20 10:54 UTC, achingbrain approved these changes
LGTM, just needs the gh url for aegir removing.

2020-11-20 12:09 UTC, merged